### ISSUE TITLE
Bug tinydb

### ISSUE THREAD

**Issue by soermejo** [msiemens/tinydb#301]
<_io.TextIOWrapper name='store.json' mode='r+' encoding='ANSI_X3.4-1968'>
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from db import base as db
  File "/root/InactiveX/db/base.py", line 7, in <module>
    db = TinyDB('store.json')
  File "/usr/local/lib/python3.6/dist-packages/tinydb/database.py", line 161, in __init__
    self._table = self.table(default_table)
  File "/usr/local/lib/python3.6/dist-packages/tinydb/database.py", line 191, in table
    table = table_class(self._cls_storage_proxy(self._storage, name), name, **options)
  File "/usr/local/lib/python3.6/dist-packages/tinydb/database.py", line 288, in __init__
    data = self._read()
  File "/usr/local/lib/python3.6/dist-packages/tinydb/database.py", line 395, in _read
    return self._storage.read()
  File "/usr/local/lib/python3.6/dist-packages/tinydb/database.py", line 85, in read
    raw_data = self._storage.read() or {}
  File "/usr/local/lib/python3.6/dist-packages/tinydb/storages.py", line 107, in read
    return json.load(self._handle)
ValueError: Trailing data

I was doing a simple update and then same ValueError: Trailing data. Then i tried to start again the db, but this error occurs again.

**Comment by msiemens** [comment]
Hey @soermejo,

it seems like your JSON file has gotten corrupted. It appears like there is garbage data after the end of the JSON object that is stored in your file (even if it's just a newline maybe).
