### ISSUE TITLE
RuntimeError: Empty query was evaluated

### ISSUE THREAD

**Issue by tavallaie** [msiemens/tinydb#339]
when I use 
`User = Query()`
`db.search(User.name.exists())`
it only works once and after that I got this error: 
`Empty query was evaluated`
but with downgrading to 3.15 it works! 
Also, someone asked it [before](https://stackoverflow.com/questions/30035284/querydict-object-has-no-attribute-caption-in-django/30035489)

**Comment by daidai21** [comment]
This [link](https://stackoverflow.com/questions/30035284/querydict-object-has-no-attribute-caption-in-django/30035489) has nothing to do with the above question, right?
@tavallaie

**Comment by msiemens** [comment]
Hey @tavallaie 

Which version of TinyDB are you using? I wasn't able to reproduce this error but rather noticed that TinyDB v4 doesn't have an error with this message.

**Comment by Uzay-G** [comment]
I also get an error with v4.1.1:

My code:

```python
    if db.search(user_query.type == "user" and user_query.is_admin):
```

Error:

```text
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/uzay/Documents/Projects/archivy/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/uzay/Documents/Projects/archivy/archivy/__init__.py", line 55, in <module>
    if db.search(user_query.type == "user" and user_query.is_admin):
  File "/home/uzay/Documents/Projects/archivy/venv/lib/python3.6/site-packages/tinydb/table.py", line 222, in search
    docs = [doc for doc in self if cond(doc)]
  File "/home/uzay/Documents/Projects/archivy/venv/lib/python3.6/site-packages/tinydb/table.py", line 222, in <listcomp>
    docs = [doc for doc in self if cond(doc)]
  File "/home/uzay/Documents/Projects/archivy/venv/lib/python3.6/site-packages/tinydb/queries.py", line 59, in __call__
    return self._test(value)
  File "/home/uzay/Documents/Projects/archivy/venv/lib/python3.6/site-packages/tinydb/queries.py", line 136, in notest
    raise RuntimeError('Empty query was evaluated')
RuntimeError: Empty query was evaluated
```
```

**Comment by eugene-eeo** [comment]
@Uzay-G you will need to use `&` instead of `and`:

```
user_query.type == "user" ^ user_query.is_admin
```

should work. See [query modifiers](https://tinydb.readthedocs.io/en/latest/usage.html#query-modifiers). One reason IIRC that we had to override these specific [magic methods](https://stackoverflow.com/questions/38549444/how-and-where-to-use-pythons-and-or-invert-magic-methods-properly) is because Python interprets `x and y` as `x.__bool__() and y.__bool__()`.

**Comment by Uzay-G** [comment]
Oh. Thanks!

**Comment by Uzay-G** [comment]
For other people who make the same mistake. Make sure you do:

```python
(user_query.type == "user") & (user_query.is_admin)
```
or the & operator will take precedence and fail

**Comment by eugene-eeo** [comment]
:facepalm: yes! my bad

**Comment by msiemens** [comment]
Closing due to inactivity.
