### ISSUE TITLE
Memory error with db.insert

### ISSUE THREAD

**Issue by UnlimitedCoder** [msiemens/tinydb#463]
My DB file size has increased to 270mb and now it is giving a memory error. is there a limit on memory?
Traceback (most recent call last):
  File "D:/others/pyth/DataExtractor/DataCollector.py", line 37, in featchData
    db.insert(storedResponse)
  File "D:\others\pyth\DataExtractor\venv\lib\site-packages\tinydb\table.py", line 171, in insert
    self._update_table(updater)
  File "D:\others\pyth\DataExtractor\venv\lib\site-packages\tinydb\table.py", line 736, in _update_table
    self._storage.write(tables)
  File "D:\others\pyth\DataExtractor\venv\lib\site-packages\tinydb\storages.py", line 136, in write
    self._handle.write(serialized)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
MemoryError

**Comment by MrPigss** [comment]
This can be because a couple of things.

- You don't have enough memory installed or another program is using all of it. (check taskmanager)
- You are using 32 bit python wich can only adress 4gb memory. (install 64 bit version)
- A bug (in your or someone elses code) caused this.

I'll try and see if I can replicate it on my machine.

**Comment by MrPigss** [comment]
I tried it on my machine:
- windows 11
- 16GB memory
- python 3.9 64bit

The size of the file i used was 464mb and i did not run into any problem.

To temporaily solve the issue you might like [BetterJSONStorage](https://pypi.org/project/BetterJSONStorage/) for TinyDB, 
It is quite a bit faster than the default storage, and uses a less memory. 

Also in the terminal run the python command
```powershell
python
```
On the first line of ouput it should say it is 64 bit. 
```powershell
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

If not, install the 64 bit version [here](https://www.python.org/downloads/windows/)

**Comment by UnlimitedCoder** [comment]
Did you try to insert ?, the only insert has the issue not search. Currently, I have resolved the issue by splitting the dbs across days(db with date name in them) since my queries will not have anything which requires data across days
My system configuration is 
windows 10
16gb ram
and below python information
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by msiemens** [comment]
@UnlimitedCoder Could you run `import sys;print("%x" % sys.maxsize, sys.maxsize > 2**32)` in your Python shell and post the results here? It is possible that you have a 32 bit Python implementation running on a 64 bit Windows.

If you are in fact running a 64 bit Python implementation, the error may be caused by your application causing a lot of objects to be created in other places except the database code. There's also the possibility that you have somehow created a memory leak by creating multiple objects that refer to each other and thus create a reference cycle (see https://stackoverflow.com/questions/9910774/what-is-a-reference-cycle-in-python). In this case your memory usage will grow basically indefenetly because Python cannot clean up these objects due to the presence of the reference cycle.

But if TinyDB is in fact the main cause of memory usage, I fear that you're reaching the limits of what TinyDB is capable of handling. In this case you might look into using SQLite which is embedded with Python and is known for its performance. 

Another honestly really hacky option would be to import the `gc` module and run `gc.collect()` after having processed large amounts of data so Python can clean up all unused objects from memory.

**Comment by msiemens** [comment]
Closing due to inactivity. Feel free to re-open it it's still an issue.
