### ISSUE TITLE
Error creating a db

### ISSUE THREAD

**Issue by lormayna** [msiemens/tinydb#57]
Hi, I'm trying to create a DB on a Debian VM.
This is the error that I get:

>>> db = TinyDB('db.json')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lorenzo/rubygram/local/lib/python2.7/site-packages/tinydb/database.py", line 50, in __init__
    self._table = self.table('_default')
  File "/home/lorenzo/rubygram/local/lib/python2.7/site-packages/tinydb/database.py", line 79, in table
    table = table_class(name, self, **options)
  File "/home/lorenzo/rubygram/local/lib/python2.7/site-packages/tinydb/database.py", line 212, in __init__
    old_ids = self._read().keys()
  File "/home/lorenzo/rubygram/local/lib/python2.7/site-packages/tinydb/database.py", line 276, in _read
    data[eid] = Element(raw_data[key], eid)
  File "/home/lorenzo/rubygram/local/lib/python2.7/site-packages/tinydb/database.py", line 21, in __init__
    self.update(value)
ValueError: dictionary update sequence element #0 has length 15; 2 is required

**Comment by msiemens** [comment]
Could you post the `db.json` file that causes this issue?

**Comment by msiemens** [comment]
@lordjabez, could you post the db.json that caused the error you had? Is this error reproducible with the latest version of TinyDB?

**Comment by lordjabez** [comment]
I think you meant @lormayna. :)

**Comment by msiemens** [comment]
@lordjabez Oops, you're right :sweat_smile:

**Comment by msiemens** [comment]
Closing as not reproducible
